name: Lint

on: push

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
        cache: 'yarn'
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run eslint lib/* lib/pdf/* --ext .js

